name: Make CV PDF
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    branches:
      - gh-pages
jobs:
  Make-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: html to pdf
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./whipp-CV.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
